//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTagApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMMASTER
    {
        public byte SNO { get; set; }
        public string Name { get; set; }
        public string IName { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
    }
}
