//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTagApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileChange
    {
        public int S_NO { get; set; }
        public string VehicleNumber { get; set; }
        public string OldMobileNumber { get; set; }
        public string NewMobileNumber { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
