//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTagApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMMASTER
    {
        public short SNO { get; set; }
        public string PARTYNAME { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string AccNO { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public string EmailID { get; set; }
        public string GSTN { get; set; }
        public string PAN { get; set; }
    }
}
